POST http://localhost:8000/api/currencies
Content-Type: application/json
Accept: application/json

{
    "code": "USD"
}

###
POST http://localhost:8000/api/currencies
Content-Type: application/json
Accept: application/json

{
    "code_list": ["NZD", "OMR", "RUB"]
}

###
POST http://localhost:8000/api/currencies
Content-Type: application/json
Accept: application/json

{
    "number": 600
}

###
POST http://localhost:8000/api/currencies
Content-Type: application/json
Accept: application/json

{
    "number_list": ["950", "446", "480"]
}

###
